FROM java-parser-cli-base:latest

WORKDIR /usr/src/app

RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y gnupg2 apt-transport-https ca-certificates
RUN wget -O - https://debian.neo4j.org/neotechnology.gpg.key | apt-key add -
RUN echo 'deb https://debian.neo4j.org/repo stable/' | tee -a /etc/apt/sources.list.d/neo4j.list
RUN apt-get update
RUN apt-get install -y neo4j=1:3.5.3

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r ./requirements.txt

COPY ./src ./

CMD [ "python3", "-u", "worker.py" ]